spring:
  application:
    name: microservicecloud-config-client
---
spring:
  profiles: dev
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #Eureka Server查询注册地址
    register-with-eureka: false
---
spring:
  profiles: test
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka #Eureka Server查询注册地址
    register-with-eureka: false